<?php

namespace Blog\ArticlesBundle\Repository;

/**
 * DefaultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultsRepository extends \Doctrine\ORM\EntityRepository
{
}
